repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.75.0
  hooks:
    - id: terraform_fmt
    - id: terragrunt_fmt
    - id: terraform_tflint

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: check-yaml
      exclude: 'helm/'
#    - id: trailing-whitespace
    - id: check-json
    - id: check-toml
    - id: check-merge-conflict
#    - id: end-of-file-fixer
    - id: detect-private-key
    - id: check-case-conflict
#    - id: mixed-line-ending
#      args:
#      - --fix=lf

- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      language_version: python3
